---
- name: Add wheezy-backports Repository
  sudo: yes
  apt_repository: repo='deb http://ftp.debian.org/debian/ wheezy-backports main' state=present

- name: Installs haproxy load balancer
  apt: pkg=haproxy state=installed update_cache=yes default_release=wheezy-backports

- name: Pushes configuration
  template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
  notify:
    - restart haproxy

- name: Sets default starting flag to 1
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify:
    - restart haproxy